### ISSUE TITLE
Add stars using badges

### ISSUE THREAD

**Issue by nitrocode** [planetjekyll/awesome-jekyll-editors#12]
The [ddavison/github-badges](https://github.com/ddavison/github-badges) project provides a website that gets stars and creates images in the form of _badges_ so you don't have to update the README every time a new star is attributed to a project.

For example, here is the [jekyll/jekyll-admin](https://github.com/jekyll/jekyll-admin) project badge

![jekyll/jekyll-admin](http://githubbadges.com/star.svg?user=jekyll&repo=jekyll-admin&background=007ecg&color=bbb&style=flat)

URL: http://githubbadges.com/star.svg?user=jekyll&repo=jekyll-admin&background=007ecg&color=bbb&style=flat

I noticed this because the README.md file shows a very old number of stars for the jekyll-admin project.

**Comment by edheltzel** [comment]
Not a bad idea... I've got some time before the new year to knock it out, but PRs are welcome also.

**Comment by geraldb** [comment]
Not really a fan of badges because they are images (and worse require a web request for each badge and possibly even more on the "backend").  I'm a big fan of text, text, text as the past, present, and future of publishing :-).   

Also note the page uses a "structured text" format - so in theory (or in practice too) you can auto-update the stars or check if the github repo is alive etc.

**Comment by nitrocode** [comment]
Yea that's true. I suppose you could auto update the stars periodically in a daily or weekly cron.

**Comment by geraldb** [comment]
Thanks for your suggestion anyways. Help and updates always welcome. Happy new year 2019! Cheers.
